#!/usr/bin/env python3
"""
gallery.py — Regenerate the marketing screenshot gallery markdown.

Reads latest/ and writes marketing/screenshots-gallery.md with grouped
image embeds (Landing pages / Tools / SEO pages). Uses relative paths
that resolve when the gallery is opened from the marketing/ folder.

Usage:
    python3 gallery.py
    python3 gallery.py --out /some/other/gallery.md
"""

from __future__ import annotations

import argparse
import datetime as dt
import os
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
LATEST_DIR = HERE / "latest"
LANDING_ROOT = HERE.parent.parent  # r5tools-landing/
DEFAULT_OUT = LANDING_ROOT / "marketing" / "screenshots-gallery.md"

# Grouping: (heading, name-prefix-matcher)
GROUPS = [
    ("Landing Pages", lambda n: n in {
        "homepage-hero", "homepage-ko-hero", "refer", "cheat-sheet",
        "waitlist", "faq", "leaderboard", "roadmap", "status",
    }),
    ("Tools", lambda n: n in {
        "hive-grid", "roster", "access-codes",
        "city-capture", "coal-burn", "freeze-risk", "heat-simulator",
        "landing-planner", "profile-studio", "season-timeline", "vs-days",
    }),
    ("SEO Pages", lambda n: n.startswith("seo-")),
]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()

    if not LATEST_DIR.exists():
        print(f"error: {LATEST_DIR} does not exist. Run capture.py first.", file=sys.stderr)
        return 2

    # Collect viewport shots only (skip -full siblings for the top gallery,
    # link them beneath each thumbnail)
    all_pngs = sorted(p for p in LATEST_DIR.glob("*.png") if not p.stem.endswith("-full"))
    if not all_pngs:
        print(f"error: no PNGs in {LATEST_DIR}", file=sys.stderr)
        return 2

    args.out.parent.mkdir(parents=True, exist_ok=True)

    # Compute paths relative to the gallery file's parent for portable md
    def rel(p: Path) -> str:
        return os.path.relpath(p, args.out.parent)

    grouped: dict[str, list[Path]] = {name: [] for name, _ in GROUPS}
    other: list[Path] = []
    for p in all_pngs:
        stem = p.stem
        placed = False
        for group_name, matcher in GROUPS:
            if matcher(stem):
                grouped[group_name].append(p)
                placed = True
                break
        if not placed:
            other.append(p)

    lines: list[str] = []
    lines.append("# r5tools screenshot gallery")
    lines.append("")
    lines.append(f"_Auto-generated by `automation/screenshots/gallery.py` on {dt.date.today().isoformat()}._")
    lines.append("")
    lines.append(f"{len(all_pngs)} screenshots. Full-page versions available alongside each viewport shot.")
    lines.append("")

    def emit_group(title: str, files: list[Path]):
        if not files:
            return
        lines.append(f"## {title}")
        lines.append("")
        for p in files:
            full = p.with_name(f"{p.stem}-full.png")
            lines.append(f"### {p.stem}")
            lines.append("")
            lines.append(f"![{p.stem}]({rel(p)})")
            lines.append("")
            if full.exists():
                lines.append(f"[Full-page]({rel(full)})")
                lines.append("")
        lines.append("")

    for group_name, _ in GROUPS:
        emit_group(group_name, grouped[group_name])
    emit_group("Other", other)

    args.out.write_text("\n".join(lines))
    print(f"wrote {args.out}  ({len(all_pngs)} shots)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
